// Generated by https://quicktype.io


interface BaseServerResponseGet{
  status:  number;
  succes:  boolean;
  message: string;
}

//!Services types -----------------------------------><
//!Esto lo tengo que reutilizar con las otras respuestas
export interface ResToGetServices extends BaseServerResponseGet {
  data:   ServiceType[];
}

export interface ServiceType {
  id:                  number;
  title:               string;
  description:         string;
  createdAt:           string;
  updatedAt:           string;
  Oritentation:        Oritentation[];
  CoverImageToService: CoverImageToService[];
}

export interface CoverImageToService {
  id:                     number;
  url:                    string;
  createdAt:              string;
  updatedAt:              string;
  setThumbnailImageTo:    null;
  setCoverImageTo:        null;
  setCoverImageToService: number;
}

export interface Oritentation {
  id:                         number;
  title:                      string;
  createdAt:                  string;
  updatedAt:                  string;
  Service_ServiceOrientation: ServiceServiceOrientation;
}

export interface ServiceServiceOrientation {
  createdAt:            string;
  updatedAt:            string;
  ServiceOrientationId: number;
  ServiceId:            number;
}
//!Services types -----------------------------------><


// Generated by https://quicktype.io
//!SubServices types -----------------------------------><
export interface ResToGetSubServices extends BaseServerResponseGet{
  data:SubServiceTypes[];
}

export interface SubServiceTypes {
  id:                    number;
  title:                 string;
  resume:                string;
  description:           string;
  createdAt:             string;
  updatedAt:             string;
  setTheBelongToService: number;
  BelongToTheService:    BelongToTheService;
}

export interface BelongToTheService {
  id:          number;
  title:       string;
  description: string;
  createdAt:   string;
  updatedAt:   string;
}
//!SubServices types -----------------------------------><


// Generated by https://quicktype.io
//!Aversiting types types -----------------------------------><

export interface ResToGetSubAdversit extends BaseServerResponseGet {
  data:    AdvertisingType[];
  status:  number;
  succes:  boolean;
  message: string;
}

export interface AdvertisingType {
  id:             number;
  title:          string;
  description:    string;
  summary:        string;
  aside:          string;
  footer:         string;
  createdAt:      string;
  updatedAt:      string;
  ThumbnailImage: ThumbnailImage[];
}

export interface ThumbnailImage {
  id:                     number;
  url:                    string;
  createdAt:              string;
  updatedAt:              string;
  setThumbnailImageTo:    number;
  setCoverImageTo:        null;
  setCoverImageToService: null;
}
//!Aversiting types types -----------------------------------><



