import Advertisings from "@/components/advertisings/advertisings";
import Head from "next/head";
import styes from "../styles/index.module.scss";
import Carrousel from "@/components/carrousel/carrousel";
import Link from "next/link";
export default function Home() {
  return (
    <>
      <Head>
        <title>Fisica Unse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styes.container}>
        <Carrousel imageEdit={[]} locationToEdit="" />
        <Advertisings />
        <Link href="/assetsReference" className={styes.assetsReference}>
          assets reference
        </Link>
      </main>
    </>
  );
}
