import Advertisings from "@/components/advertisings/advertisings";
import Head from "next/head";
import styes from "../styles/index.module.scss";
import Carrousel from "@/components/carrousel/carrousel";
import { verificationToken } from "@/helpers/verifyToken";
import ShowImage from "@/components/showImage/showImage";
export default function Home() {
  return (
    <>
      <Head>
        <title>UnseApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styes.container}>
        <Carrousel imageEdit={[]} locationToEdit="" />
        <Advertisings />
      </main>
    </>
  );
}
